apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the Deployment
  name: datamon-dev-node
spec:
  nodeName: gke-onec-dev-platform-pool-bd78fb74-362
  containers:
    - name: dev
      image: golang:1.11-alpine
      tty: true
      stdin: true
      volumeMounts:
        - name: credentials
          readOnly: true
          mountPath: "/etc/datamon-creds"
        - name: logs
          mountPath: /logs
  volumes:
    - name: credentials
      secret:
        secretName: gcs-credentials
    - name: logs
      hostPath:
        path: /var/log



